server:
  port: 8083

spring:
  application:
    name: grad-milestone-second
  security:
    user:
      name: user
      password: password
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb

  datasource:
    url: jdbc:postgresql://localhost:5433/grad-milestone-second
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

jpa:
  generate-ddl: false
  hibernate:
    dialect: PostgreSQLDialect
    ddl-auto: none
    show-sql: true

flyway:
  baselineOnMigrate: true


