server:
  port: 8083

spring:
  application:
    name: grad-milestone-second

  datasource:
    url: jdbc:postgresql://localhost:5433/grad-milestone-second
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

jpa:
  generate-ddl: false
  hibernate:
    dialect: PostgreSQLDialect
    ddl-auto: none
    show-sql: true

flyway:
  baselineOnMigrate: true
