server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

jpa:
  generate-ddl: false
  hibernate:
    dialect: PostgreSQLDialect
    ddl-auto: none
    show-sql: true
    format-sql: true

flyway:
  baselineOnMigrate: true
